issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters: [gosec]

    # See https://github.com/kjschnei001/jaeger/issues/4488
    - path: internal/grpctest/
      linters: [staticcheck]

    - linters: [gocritic]
      text: "dupArg"
    - linters: [gocritic]
      text: "exitAfterDefer"
    - linters: [gocritic]
      text: "appendAssign"
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - errcheck
  enable:
    - bidichk
    - contextcheck
    - depguard
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - govet
    - misspell

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - io/ioutil
    packages-with-error-message:
      - io/ioutil: "Use os or io instead of io/ioutil"
  goimports:
    local-prefixes: github.com/kjschnei001/jaeger
  gosec:
    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G104
      - G107
      - G404
      - G601
  gosimple:
    go: "1.20"

run:
  go: "1.20"
  timeout: 20m
  skip-dirs:
    - mocks
    - thrift-0.9.2
    - .*-gen
  skip-files:
    - ".*.pb.go$"
